# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gossip.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 34, 1, "", "gossip.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cgossip.proto\x12\x16org.solana.sealevel.v1\x1a\x0emetadata.proto")\n\x13GossipMessageBinary\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta",\n\x14\x41\x63\x63\x65ptsGossipMessage\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid"\xe4\x01\n\x14GossipMessageFixture\x12\x43\n\x08metadata\x18\x01 \x01(\x0b\x32\'.org.solana.sealevel.v1.FixtureMetadataR\x08metadata\x12\x41\n\x05input\x18\x02 \x01(\x0b\x32+.org.solana.sealevel.v1.GossipMessageBinaryR\x05input\x12\x44\n\x06output\x18\x03 \x01(\x0b\x32,.org.solana.sealevel.v1.AcceptsGossipMessageR\x06outputb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gossip_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GOSSIPMESSAGEBINARY"]._serialized_start = 56
    _globals["_GOSSIPMESSAGEBINARY"]._serialized_end = 97
    _globals["_ACCEPTSGOSSIPMESSAGE"]._serialized_start = 99
    _globals["_ACCEPTSGOSSIPMESSAGE"]._serialized_end = 143
    _globals["_GOSSIPMESSAGEFIXTURE"]._serialized_start = 146
    _globals["_GOSSIPMESSAGEFIXTURE"]._serialized_end = 374
# @@protoc_insertion_point(module_scope)
