# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serialize.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 4, "", "serialize.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fserialize.proto\x12\x16org.solana.sealevel.v1"a\n\x0bVmMemRegion\x12\x17\n\x07vm_addr\x18\x01 \x01(\x04R\x06vmAddr\x12\x18\n\x07\x63ontent\x18\x02 \x01(\x0cR\x07\x63ontent\x12\x1f\n\x0bis_writable\x18\x03 \x01(\x08R\nisWritable"m\n\x14InstrSerializeResult\x12\x16\n\x06result\x18\x01 \x01(\x05R\x06result\x12=\n\x07regions\x18\x02 \x03(\x0b\x32#.org.solana.sealevel.v1.VmMemRegionR\x07regionsb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "serialize_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_VMMEMREGION"]._serialized_start = 43
    _globals["_VMMEMREGION"]._serialized_end = 140
    _globals["_INSTRSERIALIZERESULT"]._serialized_start = 142
    _globals["_INSTRSERIALIZERESULT"]._serialized_end = 251
# @@protoc_insertion_point(module_scope)
