# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shred.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 4, "", "shred.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bshred.proto\x12\x16org.solana.sealevel.v1"!\n\x0bShredBinary\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta"U\n\nDataHeader\x12\x1d\n\nparent_off\x18\x01 \x01(\rR\tparentOff\x12\x14\n\x05\x66lags\x18\x02 \x01(\rR\x05\x66lags\x12\x12\n\x04size\x18\x03 \x01(\rR\x04size"T\n\nCodeHeader\x12\x19\n\x08\x64\x61ta_cnt\x18\x01 \x01(\rR\x07\x64\x61taCnt\x12\x19\n\x08\x63ode_cnt\x18\x02 \x01(\rR\x07\x63odeCnt\x12\x10\n\x03idx\x18\x03 \x01(\rR\x03idx"\xa7\x02\n\x0bParsedShred\x12\x1c\n\tsignature\x18\x01 \x01(\tR\tsignature\x12\x18\n\x07variant\x18\x02 \x01(\rR\x07variant\x12\x12\n\x04slot\x18\x03 \x01(\x04R\x04slot\x12\x10\n\x03idx\x18\x04 \x01(\rR\x03idx\x12\x18\n\x07version\x18\x05 \x01(\rR\x07version\x12\x1e\n\x0b\x66\x65\x63_set_idx\x18\x06 \x01(\rR\tfecSetIdx\x12\x38\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32".org.solana.sealevel.v1.DataHeaderH\x00R\x04\x64\x61ta\x12\x38\n\x04\x63ode\x18\x08 \x01(\x0b\x32".org.solana.sealevel.v1.CodeHeaderH\x00R\x04\x63odeB\x0c\n\nshred_type"$\n\x0c\x41\x63\x63\x65ptsShred\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05validb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "shred_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SHREDBINARY"]._serialized_start = 39
    _globals["_SHREDBINARY"]._serialized_end = 72
    _globals["_DATAHEADER"]._serialized_start = 74
    _globals["_DATAHEADER"]._serialized_end = 159
    _globals["_CODEHEADER"]._serialized_start = 161
    _globals["_CODEHEADER"]._serialized_end = 245
    _globals["_PARSEDSHRED"]._serialized_start = 248
    _globals["_PARSEDSHRED"]._serialized_end = 543
    _globals["_ACCEPTSSHRED"]._serialized_start = 545
    _globals["_ACCEPTSSHRED"]._serialized_end = 581
# @@protoc_insertion_point(module_scope)
