import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

_sym_db = _symbol_database.Default()
from . import context_pb2 as context__pb2
from . import txn_pb2 as txn__pb2
from . import metadata_pb2 as metadata__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="block.proto",
    package="org.solana.sealevel.v1",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x0bblock.proto\x12\x16org.solana.sealevel.v1\x1a\rcontext.proto\x1a\ttxn.proto\x1a\x0emetadata.proto"\x8b\x02\n\x0cBlockContext\x12:\n\x04txns\x18\x01 \x03(\x0b2,.org.solana.sealevel.v1.SanitizedTransaction\x126\n\x0bacct_states\x18\x02 \x03(\x0b2!.org.solana.sealevel.v1.AcctState\x12\x17\n\x0fblockhash_queue\x18\x03 \x03(\x0c\x125\n\x08slot_ctx\x18\x04 \x01(\x0b2#.org.solana.sealevel.v1.SlotContext\x127\n\tepoch_ctx\x18\x05 \x01(\x0b2$.org.solana.sealevel.v1.EpochContext"Q\n\x0cBlockEffects\x12\x11\n\thas_error\x18\x01 \x01(\x08\x12\x1b\n\x13slot_capitalization\x18\x02 \x01(\x04\x12\x11\n\tbank_hash\x18\x03 \x01(\x0c"´\x01\n\x0cBlockFixture\x129\n\x08metadata\x18\x01 \x01(\x0b2\'.org.solana.sealevel.v1.FixtureMetadata\x123\n\x05input\x18\x02 \x01(\x0b2$.org.solana.sealevel.v1.BlockContext\x124\n\x06output\x18\x03 \x01(\x0b2$.org.solana.sealevel.v1.BlockEffectsb\x06proto3'
    ),
    dependencies=[
        context__pb2.DESCRIPTOR,
        txn__pb2.DESCRIPTOR,
        metadata__pb2.DESCRIPTOR,
    ],
)
_BLOCKCONTEXT = _descriptor.Descriptor(
    name="BlockContext",
    full_name="org.solana.sealevel.v1.BlockContext",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="txns",
            full_name="org.solana.sealevel.v1.BlockContext.txns",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="acct_states",
            full_name="org.solana.sealevel.v1.BlockContext.acct_states",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="blockhash_queue",
            full_name="org.solana.sealevel.v1.BlockContext.blockhash_queue",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="slot_ctx",
            full_name="org.solana.sealevel.v1.BlockContext.slot_ctx",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="epoch_ctx",
            full_name="org.solana.sealevel.v1.BlockContext.epoch_ctx",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=349,
)
_BLOCKEFFECTS = _descriptor.Descriptor(
    name="BlockEffects",
    full_name="org.solana.sealevel.v1.BlockEffects",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="has_error",
            full_name="org.solana.sealevel.v1.BlockEffects.has_error",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="slot_capitalization",
            full_name="org.solana.sealevel.v1.BlockEffects.slot_capitalization",
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="bank_hash",
            full_name="org.solana.sealevel.v1.BlockEffects.bank_hash",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=351,
    serialized_end=432,
)
_BLOCKFIXTURE = _descriptor.Descriptor(
    name="BlockFixture",
    full_name="org.solana.sealevel.v1.BlockFixture",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="metadata",
            full_name="org.solana.sealevel.v1.BlockFixture.metadata",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="input",
            full_name="org.solana.sealevel.v1.BlockFixture.input",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="output",
            full_name="org.solana.sealevel.v1.BlockFixture.output",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=435,
    serialized_end=615,
)
_BLOCKCONTEXT.fields_by_name["txns"].message_type = txn__pb2._SANITIZEDTRANSACTION
_BLOCKCONTEXT.fields_by_name["acct_states"].message_type = context__pb2._ACCTSTATE
_BLOCKCONTEXT.fields_by_name["slot_ctx"].message_type = context__pb2._SLOTCONTEXT
_BLOCKCONTEXT.fields_by_name["epoch_ctx"].message_type = context__pb2._EPOCHCONTEXT
_BLOCKFIXTURE.fields_by_name["metadata"].message_type = metadata__pb2._FIXTUREMETADATA
_BLOCKFIXTURE.fields_by_name["input"].message_type = _BLOCKCONTEXT
_BLOCKFIXTURE.fields_by_name["output"].message_type = _BLOCKEFFECTS
DESCRIPTOR.message_types_by_name["BlockContext"] = _BLOCKCONTEXT
DESCRIPTOR.message_types_by_name["BlockEffects"] = _BLOCKEFFECTS
DESCRIPTOR.message_types_by_name["BlockFixture"] = _BLOCKFIXTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
BlockContext = _reflection.GeneratedProtocolMessageType(
    "BlockContext",
    (_message.Message,),
    dict(DESCRIPTOR=_BLOCKCONTEXT, __module__="block_pb2"),
)
_sym_db.RegisterMessage(BlockContext)
BlockEffects = _reflection.GeneratedProtocolMessageType(
    "BlockEffects",
    (_message.Message,),
    dict(DESCRIPTOR=_BLOCKEFFECTS, __module__="block_pb2"),
)
_sym_db.RegisterMessage(BlockEffects)
BlockFixture = _reflection.GeneratedProtocolMessageType(
    "BlockFixture",
    (_message.Message,),
    dict(DESCRIPTOR=_BLOCKFIXTURE, __module__="block_pb2"),
)
_sym_db.RegisterMessage(BlockFixture)
