import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor.FileDescriptor(
    name="instr_v2.proto",
    package="fd.v2",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x0einstr_v2.proto\x12\x05fd.v2"B\n\tInstrAcct\x12\r\n\x05index\x18\x01 \x01(\r\x12\x13\n\x0bis_writable\x18\x02 \x01(\x08\x12\x11\n\tis_signer\x18\x03 \x01(\x08"B\n\x08InstrEnv\x12\x16\n\x0eprogram_id_idx\x18\x01 \x01(\r\x12\x10\n\x08accounts\x18\x02 \x01(\x0c\x12\x0c\n\x04data\x18\x03 \x01(\x0c"2\n\x0cInstrEffects\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x12\n\ncustom_err\x18\x02 \x01(\rb\x06proto3'
    ),
)
_INSTRACCT = _descriptor.Descriptor(
    name="InstrAcct",
    full_name="fd.v2.InstrAcct",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="index",
            full_name="fd.v2.InstrAcct.index",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="is_writable",
            full_name="fd.v2.InstrAcct.is_writable",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="is_signer",
            full_name="fd.v2.InstrAcct.is_signer",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=91,
)
_INSTRENV = _descriptor.Descriptor(
    name="InstrEnv",
    full_name="fd.v2.InstrEnv",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="program_id_idx",
            full_name="fd.v2.InstrEnv.program_id_idx",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="accounts",
            full_name="fd.v2.InstrEnv.accounts",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="fd.v2.InstrEnv.data",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=93,
    serialized_end=159,
)
_INSTREFFECTS = _descriptor.Descriptor(
    name="InstrEffects",
    full_name="fd.v2.InstrEffects",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="result",
            full_name="fd.v2.InstrEffects.result",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="custom_err",
            full_name="fd.v2.InstrEffects.custom_err",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=161,
    serialized_end=211,
)
DESCRIPTOR.message_types_by_name["InstrAcct"] = _INSTRACCT
DESCRIPTOR.message_types_by_name["InstrEnv"] = _INSTRENV
DESCRIPTOR.message_types_by_name["InstrEffects"] = _INSTREFFECTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
InstrAcct = _reflection.GeneratedProtocolMessageType(
    "InstrAcct",
    (_message.Message,),
    dict(DESCRIPTOR=_INSTRACCT, __module__="instr_v2_pb2"),
)
_sym_db.RegisterMessage(InstrAcct)
InstrEnv = _reflection.GeneratedProtocolMessageType(
    "InstrEnv",
    (_message.Message,),
    dict(DESCRIPTOR=_INSTRENV, __module__="instr_v2_pb2"),
)
_sym_db.RegisterMessage(InstrEnv)
InstrEffects = _reflection.GeneratedProtocolMessageType(
    "InstrEffects",
    (_message.Message,),
    dict(DESCRIPTOR=_INSTREFFECTS, __module__="instr_v2_pb2"),
)
_sym_db.RegisterMessage(InstrEffects)
