# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Account(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Account()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAccount(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Account
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Account
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from org.solana.sealevel.v2.Pubkey import Pubkey
            obj = Pubkey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Account
    def Lamports(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Account
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Account
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Account
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Account
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Account
    def Executable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Account
    def Owner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from org.solana.sealevel.v2.Pubkey import Pubkey
            obj = Pubkey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AccountStart(builder):
    builder.StartObject(5)

def Start(builder):
    AccountStart(builder)

def AccountAddAddress(builder, address):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)

def AddAddress(builder, address):
    AccountAddAddress(builder, address)

def AccountAddLamports(builder, lamports):
    builder.PrependUint64Slot(1, lamports, 0)

def AddLamports(builder, lamports):
    AccountAddLamports(builder, lamports)

def AccountAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    AccountAddData(builder, data)

def AccountStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return AccountStartDataVector(builder, numElems)

def AccountAddExecutable(builder, executable):
    builder.PrependBoolSlot(3, executable, 0)

def AddExecutable(builder, executable):
    AccountAddExecutable(builder, executable)

def AccountAddOwner(builder, owner):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(owner), 0)

def AddOwner(builder, owner):
    AccountAddOwner(builder, owner)

def AccountEnd(builder):
    return builder.EndObject()

def End(builder):
    return AccountEnd(builder)
