# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ELFLoaderCtx(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ELFLoaderCtx()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsELFLoaderCtx(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ELFLoaderCtx
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ELFLoaderCtx
    def ElfData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ELFLoaderCtx
    def ElfDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ELFLoaderCtx
    def ElfDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ELFLoaderCtx
    def ElfDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ELFLoaderCtx
    def Features(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from org.solana.sealevel.v2.FeatureSet import FeatureSet
            obj = FeatureSet()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ELFLoaderCtx
    def DeployChecks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ELFLoaderCtxStart(builder):
    builder.StartObject(3)

def Start(builder):
    ELFLoaderCtxStart(builder)

def ELFLoaderCtxAddElfData(builder, elfData):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(elfData), 0)

def AddElfData(builder, elfData):
    ELFLoaderCtxAddElfData(builder, elfData)

def ELFLoaderCtxStartElfDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartElfDataVector(builder, numElems):
    return ELFLoaderCtxStartElfDataVector(builder, numElems)

def ELFLoaderCtxAddFeatures(builder, features):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(features), 0)

def AddFeatures(builder, features):
    ELFLoaderCtxAddFeatures(builder, features)

def ELFLoaderCtxAddDeployChecks(builder, deployChecks):
    builder.PrependBoolSlot(2, deployChecks, 0)

def AddDeployChecks(builder, deployChecks):
    ELFLoaderCtxAddDeployChecks(builder, deployChecks)

def ELFLoaderCtxEnd(builder):
    return builder.EndObject()

def End(builder):
    return ELFLoaderCtxEnd(builder)
