# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LtHash(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 2048

    # LtHash
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LtHash
    def Hash(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 2)) for i in range(self.HashLength())]
        elif j >= 0 and j < self.HashLength():
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 2))
        else:
            return None

    # LtHash
    def HashAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint16Flags, self._tab.Pos + 0, self.HashLength())

    # LtHash
    def HashLength(self):
        return 1024

    # LtHash
    def HashIsNone(self):
        return False


def CreateLtHash(builder, hash):
    builder.Prep(2, 2048)
    for _idx0 in range(1024 , 0, -1):
        builder.PrependUint16(hash[_idx0-1])
    return builder.Offset()
