# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class XXHash(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # XXHash
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # XXHash
    def Hash(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 1)) for i in range(self.HashLength())]
        elif j >= 0 and j < self.HashLength():
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 1))
        else:
            return None

    # XXHash
    def HashAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint8Flags, self._tab.Pos + 0, self.HashLength())

    # XXHash
    def HashLength(self):
        return 8

    # XXHash
    def HashIsNone(self):
        return False


def CreateXXHash(builder, hash):
    builder.Prep(1, 8)
    for _idx0 in range(8 , 0, -1):
        builder.PrependUint8(hash[_idx0-1])
    return builder.Offset()
